### ISSUE TITLE
APL Buy Button

### ISSUE THREAD

**Issue by dothework** [alexa/skill-sample-nodejs-demo-store-amazon-pay#7]
Hi. I've added APL to this sample, and I included a buy button that triggers the same intent that voice buying triggers. But alas, the skill is silent, the buy button dies a silent death. Any advice? Can I add you to the repo and the beta of the skill so you can poke around?

Thanks! Mark

**Comment by franklin-lobb** [comment]
were you trying to share code?  If so, I couldn't find it.

The button should Send an Event to the skill, which needs to be handled in your skill code, which should then be able to add the Connections.SendRequest directive.  Is all that happening and it's still silent?
